### PR TITLE
[TS] Input validation

### PR DESCRIPTION
**Pull request by dclaux**
## Related Issue
Fixes https://github.com/microsoft/AdaptiveCards/issues/3081

## Description
This PR implements input validation/input labels in the JS renderer. The implementation leverages the work that had already been done for 1.2 with changes according to the final spec.

This PR also includes designer support.

**Notes:**
I have discussed the below with Alberto and we agreed that these changes made sense. If there is a need to further discuss, I'm happy to take it offline.
- This implementation uses property names in HostConfig that differ from those used in the spec. The spec will be updated to match the terminology used in this implementation. Namely, the code uses this format:
```json
"inputs": {
	"label": {
		"inputSpacing": "small",
		"requiredInputs": {
			"suffix": "*",
			"suffixColor": "attention",
			"weight": "default",
			"color": "default",
			"size": "default",
			"isSubtle": false
		},
		"optionalInputs": {
			"color": "default",
			"weight": "default",
			"size": "default",
			"isSubtle": false
		}
	},
	"errorMessage": {
		"spacing": "small",
		"size": "default",
		"weight": "lighter",
		"color": "attention"
	}
}
```
- This implementation includes the `suffixColor` property which goes one step beyond the spec. I felt that this was necessary as I implemented the feature. I can always remove it, but I really do think we need to support it.

## How Verified
Verified manually in the designer.

Sample test payload:
```json
{
    "type": "AdaptiveCard",
    "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
    "version": "1.3",
    "body": [
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "label": "This is an optional input",
            "id": "input1"
        },
        {
            "type": "Input.Text",
            "placeholder": "Placeholder text",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "isRequired": true,
            "id": "input2",
            "regex": "abc",
            "label": "This is a required Text input. This label is intentionally long to show that it correctly wraps."
        },
        {
            "type": "Input.Date",
            "label": "This is a required Date input",
            "isRequired": true,
            "min": "6/1/2020",
            "max": "6/30/2020",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input3"
        },
        {
            "type": "Input.Time",
            "label": "This is a required Time input",
            "isRequired": true,
            "min": "08:00",
            "max": "15:00",
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input4"
        },
        {
            "type": "Input.Number",
            "placeholder": "Placeholder text",
            "label": "This is a required Number input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "min": 4,
            "max": 6,
            "id": "input5"
        },
        {
            "type": "Input.ChoiceSet",
            "choices": [
                {
                    "title": "Choice 1",
                    "value": "Choice 1"
                },
                {
                    "title": "Choice 2",
                    "value": "Choice 2"
                }
            ],
            "placeholder": "Placeholder text",
            "label": "This is a required ChoiceSet input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input6"
        },
        {
            "type": "Input.Toggle",
            "title": "New Input.Toggle",
            "label": "This is a required Toggle input",
            "isRequired": true,
            "errorMessage": "The input value is invalid. This error message is intentionally long to show that it wraps.",
            "id": "input7"
        }
    ],
    "actions": [
        {
            "type": "Action.Submit",
            "title": "Action.Submit"
        }
    ]
}
```

As initially rendered:
image

Once the action is clicked, showing validation errors:
image

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/microsoft/AdaptiveCards/pull/4197)

### CODE REVIEW

**Comment by shalinijoshi19** [comment]
@paulcam206 do we still need to manually invoke /azp run at this point on non-main and non-release branches?

**Comment by shalinijoshi19** [comment]
@jwoo-msft can you help take a look at the iOS CI failure? Thanks!

**Comment by paulcam206** [comment]
> @paulcam206 do we still need to manually invoke /azp run at this point on non-main and non-release branches? 

should run automatically, but if there's a need to run manually, we still have to use the long form of azp run...

**Comment by jwoo-msft** [comment]
> @jwoo-msft can you help take a look at the [iOS CI](https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=24530551&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=b572b116-3393-5d48-803e-9da3a99206d0&l=153) failure? is this a bad merge from main into the topic branch or something? @almedina-ms?

This is because of compilation error in shared code. I don't know why this is caught only at iOS.
```
    template<typename T>
    std::shared_ptr<T> ParseUtil::GetElementOfType(
        ParseContext& context,
        const Json::Value& json,
        AdaptiveCardSchemaKey key,
        const std::function<std::shared_ptr<T>(ParseContext& context, const Json::Value&)>& **V**)
    {
        auto el = **deserializer**(context, json);
        return el;
    }
```
V should be deserializer.

**Comment by shalinijoshi19** [comment]
> > @jwoo-msft can you help take a look at the [iOS CI](https://microsoft.visualstudio.com/AdaptiveCards/_build/results?buildId=24530551&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=b572b116-3393-5d48-803e-9da3a99206d0&l=153) failure? is this a bad merge from main into the topic branch or something? @almedina-ms?
> 
> @shalinijoshi19
> This is because of compilation error in shared code in ParseUtil.h. I don't know why this is caught only at iOS.
> 
> ```
>     template<typename T>
>     std::shared_ptr<T> ParseUtil::GetElementOfType(
>         ParseContext& context,
>         const Json::Value& json,
>         AdaptiveCardSchemaKey key,
>         const std::function<std::shared_ptr<T>(ParseContext& context, const Json::Value&)>& V)
>     {
>         auto el = deserializer(context, json);
>         return el;
>     }
> ```
> 
> V should be deserializer in the code snippet above. @almedina-ms is aware of this issue.

@almedina-ms if you are pushing out a fix for this to the main branch, can this PR be merged since JS builds actually succeeded?

**Comment by shalinijoshi19** [comment]
@dclaux / @almedina-ms  what does it mean actually for a Toggle input to have the IsRequired hint? It's a bool so why would we even support it for that Input type?

**Comment by paulcam206** [comment]
> @dclaux / @almedina-ms what does it mean actually for a Toggle input to have the IsRequired hint? It's a bool so why would we even support it for that Input type?

image
